import {beforeEach,describe,expect,it,vi} from 'vitest'
import {usePresenceStore} from '../domain/store'
import {projectFingerprints} from '../domain/proof'
import {registerWebMcp} from '../webmcp/register'
import {createPresence,stableFingerprint,type PresenceIdentity,type PresenceOperation} from '../sdk/createPresence'

type Tool={name:string;execute:(args:Record<string,unknown>)=>unknown}
const tools=new Map<string,Tool>()
const call=(name:string,args:Record<string,unknown>={})=>tools.get(name)!.execute(args) as any
const admit=()=>{call('request_admission',{reason:'I can handle Tablet while you finish Mobile.'});usePresenceStore.getState().approveAdmission()}
const freshTablet=()=>call('propose_layout_change',{componentId:'hero',breakpoint:'tablet',patch:{heroLayout:'split'},label:'Split Tablet hero',expectedRevision:usePresenceStore.getState().revision})

beforeEach(()=>{
 tools.clear();usePresenceStore.getState().reset()
 Object.defineProperty(document,'modelContext',{configurable:true,value:{registerTool:vi.fn((tool:Tool)=>tools.set(tool.name,tool))}})
 registerWebMcp()
})

describe('Presence collaboration evidence — 16 invariants',()=>{
 it('01 admission is required before inspection or proposal authority',()=>{expect(call('inspect_breakpoint',{breakpoint:'tablet'})).toMatchObject({ok:false,error:'ADMISSION_REQUIRED'});expect(call('propose_layout_change',{componentId:'hero',breakpoint:'tablet',patch:{heroGap:20},label:'Try',expectedRevision:12})).toMatchObject({ok:false,error:'ADMISSION_REQUIRED'})})
 it('02 admission request grants no authority before the human decision',()=>{call('request_admission',{reason:'Tablet please'});expect(usePresenceStore.getState().admission?.status).toBe('pending');expect(usePresenceStore.getState().admission?.grantedScopes).toHaveLength(0)})
 it('03 admitted agent can inspect Desktop Tablet and Mobile',()=>{admit();for(const breakpoint of ['desktop','tablet','mobile'])expect(call('inspect_breakpoint',{breakpoint}).breakpoint).toBe(breakpoint)})
 it('04 admitted agent can create a fresh provisional Tablet proposal',()=>{admit();expect(freshTablet()).toMatchObject({ok:true,provisional:true});expect(usePresenceStore.getState().proposal?.status).toBe('working')})
 it('05 Mobile mutation is denied with no canonical or provisional Mobile change',()=>{admit();const before=usePresenceStore.getState();const hashes=projectFingerprints(before);const result=call('propose_layout_change',{componentId:'hero',breakpoint:'mobile',patch:{heroGap:10},label:'Attack Mobile',expectedRevision:before.revision});const after=usePresenceStore.getState();expect(result).toMatchObject({ok:false,error:'SURFACE_NOT_ASSIGNED'});expect(after.revision).toBe(before.revision);expect(projectFingerprints(after).mobile).toBe(hashes.mobile);expect(after.proposal?.operations.some(op=>op.breakpoint==='mobile')??false).toBe(false)})
 it('06 Desktop reference mutation is denied and its fingerprint is unchanged',()=>{admit();const before=usePresenceStore.getState();const hash=projectFingerprints(before).desktop;expect(call('propose_layout_change',{componentId:'hero',breakpoint:'desktop',patch:{heroGap:10},label:'Attack reference',expectedRevision:before.revision})).toMatchObject({ok:false,error:'REFERENCE_LOCKED'});expect(projectFingerprints(usePresenceStore.getState()).desktop).toBe(hash)})
 it('07 agent publication is denied and the human Accept gate remains pending',()=>{admit();freshTablet();call('submit_proposal');const revision=usePresenceStore.getState().revision;expect(call('publish_proposal')).toMatchObject({ok:false,error:'HUMAN_APPROVAL_REQUIRED'});expect(usePresenceStore.getState().proposal?.status).toBe('ready');expect(usePresenceStore.getState().revision).toBe(revision)})
 it('08 stale expectedRevision is rejected before canonical Tablet mutation',()=>{admit();const base=usePresenceStore.getState().revision;const tabletHash=projectFingerprints(usePresenceStore.getState()).tablet;usePresenceStore.getState().humanChange();expect(call('propose_layout_change',{componentId:'hero',breakpoint:'tablet',patch:{heroLayout:'split'},label:'Stale Tablet',expectedRevision:base})).toMatchObject({ok:false,error:'STALE_STATE'});expect(projectFingerprints(usePresenceStore.getState()).tablet).toBe(tabletHash)})
 it('09 denied operations preserve the exact protected Mobile fingerprint',()=>{admit();const hash=projectFingerprints(usePresenceStore.getState()).mobile;call('propose_component_change',{componentId:'cta',breakpoint:'mobile',patch:{ctaFull:true},label:'Try human CTA',expectedRevision:12});expect(projectFingerprints(usePresenceStore.getState()).mobile).toBe(hash)})
 it('10 human acceptance changes Tablet atomically while Desktop and Mobile remain identical',()=>{admit();freshTablet();call('submit_proposal');const before=projectFingerprints(usePresenceStore.getState());usePresenceStore.getState().acceptProposal();const after=projectFingerprints(usePresenceStore.getState());expect(after.tablet).not.toBe(before.tablet);expect(after.mobile).toBe(before.mobile);expect(after.desktop).toBe(before.desktop);expect(usePresenceStore.getState().receipts).toHaveLength(1)})
 it('11 revocation immediately removes proposal authority',()=>{admit();call('release_role');expect(call('propose_layout_change',{componentId:'hero',breakpoint:'tablet',patch:{heroGap:10},label:'After revoke',expectedRevision:12})).toMatchObject({ok:false,error:'ADMISSION_REVOKED'})})
 it('12 deterministic reset restores seed revision fingerprints and audit truth',()=>{const seed=projectFingerprints(usePresenceStore.getState());admit();usePresenceStore.getState().humanChange();usePresenceStore.getState().reset();const reset=usePresenceStore.getState();expect(reset.revision).toBe(12);expect(projectFingerprints(reset)).toEqual(seed);expect(reset.activity[0]?.code).toBe('RESET')})

 it('13 paused agents cannot mutate until a human resumes them',()=>{admit();usePresenceStore.getState().pause();expect(call('propose_layout_change',{componentId:'hero',breakpoint:'tablet',patch:{heroGap:24},label:'Paused try',expectedRevision:12})).toMatchObject({ok:false,error:'ADMISSION_PAUSED'})})
 it('14 blocked engine outcomes produce matching structured audit events',()=>{admit();call('propose_layout_change',{componentId:'hero',breakpoint:'mobile',patch:{heroGap:9},label:'Denied',expectedRevision:12});const last=usePresenceStore.getState().activity.at(-1);expect(last).toMatchObject({kind:'authority',outcome:'blocked',code:'SURFACE_NOT_ASSIGNED',surface:'mobile'})})
 it('15 deterministic fingerprints match canonical serialized state',()=>{const a={b:2,a:[1,{z:true,y:'x'}]};const b={a:[1,{y:'x',z:true}],b:2};expect(stableFingerprint(a)).toBe(stableFingerprint(b))})
 it('16 the same Presence SDK protects a non-responsive incident application',()=>{type Doc={items:string[]};const h:PresenceIdentity={id:'h',displayName:'Human',kind:'human'},a:PresenceIdentity={id:'a',displayName:'Agent',kind:'agent'};const engine=createPresence<Doc>({applicationId:'test-incident',surfaces:[{id:'production',mode:'human-edit'},{id:'investigation',mode:'agent-propose'},{id:'timeline',mode:'reference'}],roles:[{id:'investigator',capabilities:['inspect','propose'],surfaceIds:['investigation']}],documents:{production:{items:[]},investigation:{items:[]},timeline:{items:[]}},documentAdapter:{clone:d=>({items:[...d.items]}),apply:(d,op:PresenceOperation)=>({items:[...d.items,String(op.payload.value)]})}});const req=engine.requestAdmission(a,'investigator',['investigation']);engine.grantAdmission(h,String((req as any).admissionId));const base=engine.snapshot().revision;engine.humanMutate(h,'production',{surfaceId:'production',type:'add',payload:{value:'mitigation'},intent:'mitigate'});expect(engine.propose(a,'investigator',{surfaceId:'investigation',type:'add',payload:{value:'hypothesis'},intent:'investigate',expectedRevision:base})).toMatchObject({ok:false,error:'STALE_STATE'});expect(engine.propose(a,'investigator',{surfaceId:'production',type:'add',payload:{value:'bad'},intent:'cross scope',expectedRevision:engine.snapshot().revision})).toMatchObject({ok:false,error:'SURFACE_NOT_ASSIGNED'})})
})
