import {usePresenceStore} from '../domain/store'
import {proofMetrics} from '../domain/proof'
import type {Breakpoint} from '../domain/types'

type ToolDefinition={name:string;description:string;inputSchema?:Record<string,unknown>;execute:(args:Record<string,unknown>)=>unknown}
declare global{interface Document{modelContext?:{registerTool:(tool:ToolDefinition)=>void}}}

const catalog=new Map<string,Omit<ToolDefinition,'execute'>>()
export const getWebMcpCatalog=()=>[...catalog.values()]
const objectSchema=(properties:Record<string,unknown>,required:string[]=[]):Record<string,unknown>=>({type:'object',properties,required,additionalProperties:false})
const live=()=>usePresenceStore.getState()
const breakpoint=(value:unknown):Breakpoint=>value==='desktop'||value==='mobile'?'desktop'===value?'desktop':'mobile':'tablet'
const admissionReadGate=()=>{const a=live().admission;if(!a)return{ok:false,error:'ADMISSION_REQUIRED',message:'Admission is required before the agent can inspect project surfaces.',revision:live().revision};if(a.status!=='admitted')return{ok:false,error:a.status==='revoked'?'ADMISSION_REVOKED':'ADMISSION_PENDING',message:'The agent does not currently hold inspection authority.',revision:live().revision};return null}
const structuredMutationResult=(result:any,target:Breakpoint,before:{revision:number;fingerprints:ReturnType<typeof proofMetrics>['fingerprints']})=>{const after={revision:live().revision,fingerprints:proofMetrics(live()).fingerprints};return result?.ok?{...result,revision:after.revision,provisional:true,beforeRevision:before.revision,afterRevision:after.revision,beforeFingerprints:before.fingerprints,afterFingerprints:after.fingerprints}:{...result,message:result?.error==='SURFACE_NOT_ASSIGNED'?'Mobile belongs to the human. Agent mutation blocked before state change.':result?.error==='REFERENCE_LOCKED'?'Desktop is the locked reference. Mutation blocked before state change.':result?.error==='STALE_STATE'?'The project revision changed. Stale work was rejected before mutation.':result?.error==='ADMISSION_REVOKED'?'This agent no longer has authority.':result?.error==='HUMAN_APPROVAL_REQUIRED'?'Final approval belongs to the human.':'Presence rejected the operation.',revision:after.revision,target,beforeRevision:before.revision,afterRevision:after.revision,beforeFingerprints:before.fingerprints,afterFingerprints:after.fingerprints}}

const register=(definition:ToolDefinition)=>{
 catalog.set(definition.name,{name:definition.name,description:definition.description,inputSchema:definition.inputSchema})
 document.modelContext?.registerTool({...definition,execute:(args)=>{
  const started=performance.now();const before=live().activity.at(-1)?.id
  try{
   const result=definition.execute(args)
   const after=live().activity.at(-1)?.id
   live().recordToolTrace({tool:definition.name,description:definition.description,input:args,result,durationMs:Math.max(0,Math.round((performance.now()-started)*10)/10),revision:live().revision,auditEventId:after!==before?after:undefined,at:new Date().toISOString()})
   return result
  }catch(error){
   const result={ok:false,error:'TOOL_EXECUTION_FAILED',message:error instanceof Error?error.message:String(error)}
   live().recordToolTrace({tool:definition.name,description:definition.description,input:args,result,durationMs:Math.max(0,Math.round((performance.now()-started)*10)/10),revision:live().revision,auditEventId:live().activity.at(-1)?.id,at:new Date().toISOString()})
   throw error
  }
 }})
}

export function registerWebMcp(){
 if(!document.modelContext)return false
 register({name:'inspect_presence',description:'Inspect the live Presence workspace, canonical revision, ownership, available agent seat, and admission state.',inputSchema:objectSchema({}),execute:()=>{const state=live();state.discoverAgent();const next=live();return{revision:next.revision,seat:{breakpoint:'tablet',status:next.admission?.status==='admitted'?'occupied':'unassigned'},ownership:{desktop:'reference',tablet:next.admission?.status==='admitted'?'agent-temporary':'unassigned',mobile:'human'},admission:next.admission?.status??'none',roles:['responsive-collaborator']}}})
 register({name:'inspect_available_roles',description:'Inspect the exact scoped roles Presence can grant to this external browser agent.',inputSchema:objectSchema({}),execute:()=>({roles:[{id:'responsive-collaborator',label:'Responsive collaborator',can:['inspect:desktop','inspect:tablet','inspect:mobile','propose:tablet'],cannot:['write:desktop','write:mobile','publish','accept','change:canonical-copy']} ]})})
 register({name:'request_admission',description:'Ask the human to admit this browser agent as the temporary Responsive collaborator for Tablet.',inputSchema:objectSchema({reason:{type:'string',minLength:1,maxLength:180}},['reason']),execute:args=>{live().requestAdmission(String(args.reason??'I can handle Tablet while you finish Mobile.'));return{status:'pending_user_approval',requestedRole:'responsive-collaborator',requestedScope:['inspect:desktop','inspect:tablet','inspect:mobile','propose:tablet'],humanDecisionRequired:true}}})
 register({name:'inspect_admission',description:'Inspect whether this browser agent is discovered, pending, admitted, paused, or revoked and the currently granted scopes.',inputSchema:objectSchema({}),execute:()=>live().admission??{status:'none',grantedScopes:[]}})
 register({name:'inspect_project',description:'Inspect the live Aurora project and its current canonical revision without mutating state.',inputSchema:objectSchema({}),execute:()=>({project:'Aurora',revision:live().revision,goal:'Preserve hierarchy while adapting responsive surfaces.',proof:proofMetrics(live()).fingerprints})})
 register({name:'inspect_breakpoint',description:'Inspect one responsive surface after admission, including ownership, current revision, and canonical state fingerprint.',inputSchema:objectSchema({breakpoint:{type:'string',enum:['desktop','tablet','mobile']}},['breakpoint']),execute:args=>{const gate=admissionReadGate();if(gate)return gate;const bp=breakpoint(args.breakpoint);const m=proofMetrics(live());return{ok:true,breakpoint:bp,revision:live().revision,ownership:bp==='desktop'?'reference':bp==='mobile'?'human':'agent-seat',fingerprint:m.fingerprints[bp],design:bp==='mobile'?live().mobileDesign:bp==='tablet'?live().tabletDesign:'reference-locked'}}})
 register({name:'inspect_component',description:'Inspect a semantic component before proposing a change. Presence visibly focuses that real target.',inputSchema:objectSchema({componentId:{type:'string',minLength:1}},['componentId']),execute:args=>{const componentId=String(args.componentId);const result=live().agentInspect(componentId,`Inspecting ${componentId}`);return result.ok?{ok:true,componentId,revision:live().revision}:result}})
 register({name:'inspect_page_structure',description:'Inspect the real Aurora page structure that Presence is editing, including stable semantic component IDs and parent/child relationships.',inputSchema:objectSchema({}),execute:()=>({project:'Aurora',revision:live().revision,tree:{id:'page',type:'Page',children:[{id:'nav',type:'Navigation',children:['logo','product-links','auth-actions']},{id:'hero',type:'Section',children:['copy','media']},{id:'customer-proof',type:'LogoGroup'},{id:'features',type:'Section',children:['decision-history','agent-workflows','launch-coordination']},{id:'workflow',type:'Section',children:['brief','review','decision','build','launch']},{id:'testimonial',type:'Testimonial'},{id:'integrations',type:'LogoGroup'},{id:'conversion',type:'Section'},{id:'footer',type:'Footer'}]}})})
 register({name:'inspect_component_children',description:'Inspect valid semantic children for an Aurora component without changing state.',inputSchema:objectSchema({componentId:{type:'string',minLength:1}},['componentId']),execute:args=>{const id=String(args.componentId);const children:Record<string,string[]>={page:['nav','hero','customer-proof','features','workflow','testimonial','integrations','conversion','footer'],hero:['copy','media'],features:['decision-history','agent-workflows','launch-coordination'],workflow:['brief','review','decision','build','launch']};return{ok:true,componentId:id,children:children[id]??[],revision:live().revision}}})
 register({name:'inspect_responsive_properties',description:'Inspect the canonical responsive properties for a protected surface at the current revision.',inputSchema:objectSchema({breakpoint:{type:'string',enum:['desktop','tablet','mobile']}},['breakpoint']),execute:args=>{const gate=admissionReadGate();if(gate)return gate;const bp=breakpoint(args.breakpoint);return{ok:true,breakpoint:bp,revision:live().revision,properties:bp==='tablet'?live().tabletDesign:bp==='mobile'?live().mobileDesign:{mode:'reference-locked'},fingerprint:proofMetrics(live()).fingerprints[bp]}}})
 register({name:'inspect_constraints',description:'Inspect the capability, ownership, publication, and fresh-revision constraints enforced by the production state engine.',inputSchema:objectSchema({}),execute:()=>({desktop:{mode:'reference-locked'},tablet:{mode:'propose-only'},mobile:{mode:'human-owned'},publish:'human-only',accept:'human-only',freshRevisionRequired:true,staleWritesApply:false})})
 register({name:'inspect_recent_changes',description:'Inspect recent human, agent, and system audit events with revisions and structured authority outcomes.',inputSchema:objectSchema({}),execute:()=>live().activity.slice(-12)})
 register({name:'compare_breakpoints',description:'Compare ownership, fingerprints, and intended behavior across Desktop, Tablet, and Mobile.',inputSchema:objectSchema({}),execute:()=>{const m=proofMetrics(live());return{revision:live().revision,desktop:{owner:'REFERENCE',fingerprint:m.fingerprints.desktop},tablet:{owner:live().admission?.status==='admitted'?'YOUR AGENT':'UNASSIGNED',fingerprint:m.fingerprints.tablet},mobile:{owner:'YOU',fingerprint:m.fingerprints.mobile}}}})
 const propose=(args:Record<string,unknown>)=>{const target=breakpoint(args.breakpoint),before={revision:live().revision,fingerprints:proofMetrics(live()).fingerprints};return structuredMutationResult(live().agentPropose({componentId:String(args.componentId??''),breakpoint:target,patch:typeof args.patch==='object'&&args.patch?args.patch as Record<string,unknown>:{},label:String(args.label??'Agent proposed a Tablet change'),expectedRevision:Number(args.expectedRevision)}),target,before)}
 const mutationSchema=objectSchema({componentId:{type:'string',minLength:1},breakpoint:{type:'string',enum:['desktop','tablet','mobile']},patch:{type:'object'},label:{type:'string',minLength:1},expectedRevision:{type:'integer',minimum:0}},['componentId','breakpoint','patch','label','expectedRevision'])
 register({name:'propose_layout_change',description:'Propose a provisional responsive layout change. Presence revalidates admitted surface scope and expectedRevision immediately before the operation is recorded.',inputSchema:mutationSchema,execute:propose})
 register({name:'propose_component_change',description:'Propose a provisional component change. Human-owned and reference surfaces are blocked before mutation.',inputSchema:mutationSchema,execute:propose})
 register({name:'propose_responsive_rule',description:'Propose a provisional responsive rule on the admitted surface using optimistic concurrency control.',inputSchema:mutationSchema,execute:propose})
 register({name:'propose_component_move',description:'Propose a semantic drag/reorder of a Tablet hero component. The move is recorded as a provisional document operation, not a visual-only transform.',inputSchema:objectSchema({componentId:{type:'string',enum:['copy','visual']},toIndex:{type:'integer',minimum:0,maximum:1},expectedRevision:{type:'integer',minimum:0}},['componentId','toIndex','expectedRevision']),execute:args=>{const componentId=String(args.componentId);const toIndex=Math.max(0,Math.min(1,Number(args.toIndex)));const order=['copy','visual'].filter(x=>x!==componentId);order.splice(toIndex,0,componentId);const before={revision:live().revision,fingerprints:proofMetrics(live()).fingerprints};return structuredMutationResult(live().agentPropose({componentId:'hero',breakpoint:'tablet',patch:{heroOrder:order},label:`Moved ${componentId} to position ${toIndex+1}`,expectedRevision:Number(args.expectedRevision)}),'tablet',before)}})
 register({name:'submit_proposal',description:'Mark the current provisional Tablet proposal ready for human review. This does not publish or mutate canonical Tablet state.',inputSchema:objectSchema({}),execute:()=>live().markProposalReady()})
 register({name:'publish_proposal',description:'Attempt final publication of the current proposal. Presence deliberately rejects this for agents because final approval is human-only.',inputSchema:objectSchema({}),execute:()=>{const before={revision:live().revision,fingerprints:proofMetrics(live()).fingerprints};return structuredMutationResult(live().agentPublish(),'tablet',before)}})
 register({name:'explain_proposal',description:'Explain the current provisional Tablet proposal, base revision, affected surface, and operation count.',inputSchema:objectSchema({}),execute:()=>live().proposal?{id:live().proposal?.id,status:live().proposal?.status,baseRevision:live().proposal?.baseRevision,affectedBreakpoint:'tablet',explanation:live().proposal?.explanation,operations:live().proposal?.operations.length}:{status:'none'}})
 register({name:'inspect_proof',description:'Inspect machine-derived collaboration invariants and stable canonical fingerprints from the live production state.',inputSchema:objectSchema({}),execute:()=>proofMetrics(live())})
 register({name:'release_role',description:'Release this agent role. Presence revokes future authority immediately while preserving audit and proposal evidence.',inputSchema:objectSchema({}),execute:()=>{live().revoke();return{status:'revoked',revision:live().revision}}})
 return true
}
