import {expect,test} from '@playwright/test'

test('flagship: real human edit interrupts visible agent work, review is provisional, revoke is enforced',async({page})=>{
 await page.goto('/')
 await expect(page.getByText('Waiting for a collaborator')).toBeVisible()
 await expect(page.getByText('UNASSIGNED')).toBeVisible()
 await page.getByRole('button',{name:/Preview admission flow/i}).click()
 await expect(page.getByText('Wants this seat.')).toBeVisible()
 await expect(page.getByText('Cannot publish')).toBeVisible()
 await page.getByRole('button',{name:/Admit/i}).click()
 await expect(page.getByText('YOUR AGENT').first()).toBeVisible()

 await page.getByRole('button',{name:/Start agent work/i}).click()
 await expect(page.getByText(/Inspecting Hero/i)).toBeVisible()
 await page.waitForTimeout(800)

 // A genuine human edit changes canonical revision while the agent still holds the older read.
 const before=await page.locator('.revision').textContent()
 await page.getByText('Your product team, finally in the same orbit.').last().click()
 await expect(page.getByText(/YOU · HEADLINE/i)).toBeVisible()
 await page.getByText('TYPE').locator('..').getByRole('button').last().click()
 await expect(page.locator('.revision')).not.toHaveText(before??'')

 await expect(page.getByText('Project changed',{exact:true})).toBeVisible({timeout:5000})
 await expect(page.getByText(/working from r12/i)).toBeVisible()
 await expect(page.getByText(/Catching up/i)).toBeVisible()
 await expect(page.getByText(/Proposal ready/i)).toBeVisible({timeout:9000})
 await page.getByRole('button',{name:/Review/i}).click()
 await expect(page.getByRole('dialog',{name:/Your agent is done/i})).toBeVisible()
 const rows=page.locator('.review-change-card')
 await expect(rows.first()).toBeVisible()
 await rows.first().click()
 await expect(page.locator('.review-climax-preview .agent-focus')).toBeVisible()
 const countBefore=await rows.count()
 await rows.first().getByRole('button',{name:'Reject'}).click()
 await expect(page.locator('.review-change-card')).toHaveCount(countBefore-1)
 await page.getByRole('button',{name:/Accept .*change.*advance to r/i}).click()
 await expect(page.getByRole('dialog',{name:/Your agent is done/i})).toBeHidden()

 await page.getByRole('button',{name:/Remove agent/i}).click()
 await expect(page.getByText('Seat is empty again.')).toBeVisible()
 await expect(page.getByText('UNASSIGNED')).toBeVisible()
 await page.getByRole('button',{name:/Prove access is gone/i}).click()
 await expect(page.getByText('Blocked',{exact:true})).toBeVisible()
 await expect(page.getByText('ADMISSION_REVOKED')).toBeVisible()
})

test('mobile keeps the admission CTA above the fold and exposes a real editable Mobile surface',async({page})=>{
 await page.setViewportSize({width:393,height:852})
 await page.goto('/')
 await expect(page.getByRole('tab',{name:'Tablet'})).toHaveAttribute('aria-selected','true')
 const cta=page.getByRole('button',{name:/Preview admission flow/i})
 await expect(cta).toBeVisible()
 const box=await cta.boundingBox()
 expect(box).not.toBeNull()
 expect((box?.y??9999)+(box?.height??0)).toBeLessThan(852)
 await page.getByRole('tab',{name:'Mobile'}).click()
 await page.getByText('Your product team, finally in the same orbit.').last().click()
 await expect(page.getByText(/YOU · HEADLINE/)).toBeVisible()
 const revisionBefore=await page.locator('.topbar').getByText(/^r\d+$/).textContent().catch(()=>null)
 await page.getByText('CTA width').click()
 if(revisionBefore) await expect(page.locator('.topbar')).not.toContainText(revisionBefore)
})

test('human Mobile edits are revisioned and undoable without granting the agent any seat',async({page})=>{
 await page.goto('/')
 const before=await page.locator('.revision').textContent()
 await page.getByText('Your product team, finally in the same orbit.').last().click()
 await expect(page.getByText(/YOU · HEADLINE/)).toBeVisible()
 await page.getByText('CTA width').click()
 await expect(page.locator('.revision')).not.toHaveText(before??'')
 await expect(page.getByText('FULL')).toBeVisible()
 await page.getByRole('button',{name:'Undo'}).click()
 await expect(page.getByText('AUTO')).toBeVisible()
 await expect(page.getByText('Waiting for a collaborator')).toBeVisible()
})


test('demo director drives the flagship proof through real store actions',async({page})=>{
 await page.goto('/?demo=1')
 const guide=page.getByLabel('Flagship demo guide')
 await expect(guide).toContainText('Agent has no authority yet')
 await guide.getByRole('button',{name:/Agent requests Tablet/i}).click()
 await expect(guide).toContainText('A seat is being requested')
 await guide.getByRole('button',{name:/Admit Tablet only/i}).click()
 await expect(guide).toContainText('The agent has one scoped seat')
 await guide.getByRole('button',{name:/Start agent work/i}).click()
 await expect(guide.getByRole('button',{name:/You: change Mobile/i})).toBeVisible({timeout:7000})
 await guide.getByRole('button',{name:/You: change Mobile/i}).click()
 await expect(page.getByText(/STALE STATE|Overwrite prevented/i).first()).toBeVisible({timeout:5000})
 await expect(guide.getByRole('button',{name:/Review proposal/i})).toBeVisible({timeout:10000})
 await guide.getByRole('button',{name:/Review proposal/i}).click()
 await expect(page.getByRole('dialog',{name:/Your agent is done/i})).toBeVisible()
 const accept=page.getByRole('button',{name:/Accept .*advance to r/i})
 await accept.click()
 await expect(guide.getByRole('button',{name:/Revoke agent/i})).toBeVisible()
 await guide.getByRole('button',{name:/Revoke agent/i}).click()
 await expect(guide.getByRole('button',{name:/Prove access is gone/i})).toBeVisible()
 await guide.getByRole('button',{name:/Prove access is gone/i}).click()
 await expect(guide).toContainText('Give agents a seat. Not the keys.')
})
